# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 3.{build}
configuration: Release
platform: Any CPU

build:
  project: src\EvcProver.sln
  verbosity: minimal
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)

# branches to build
branches:
  # whitelist
  only:
    - master   
    - rc

# build cache to preserve files/folders between builds
#cache:
#  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
#  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
#  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
cache:
  - packages -> **\packages.config
  #- packages -> appveyor.yml 


skip_tags: true

pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019

artifacts:
  - path: build\Release
    name: EvcProver-v$(appveyor_build_version)-$(APPVEYOR_REPO_BRANCH)

before_build:
  - cmd: .\src\.nuget\NuGet.exe update -self
  - ps: .\src\.nuget\NuGet.exe restore .\src\EvcProver.sln

deploy:
# Deploy to GitHub Releases
# RC branch
- provider: GitHub
  tag: v$(APPVEYOR_BUILD_VERSION)-rc
  release: v$(APPVEYOR_BUILD_VERSION)-rc
  description: 'Release Candidate - v$(APPVEYOR_BUILD_VERSION)'
  auth_token:
    secure: riuun7iAbRmIkLsYhZqe58U99H/PnROepaggimQhrrp8p8gUOCYD2CyrjwvDzPdF
  on:
    branch: rc
    
- provider: GitHub
  tag: v$(APPVEYOR_BUILD_VERSION)-dev
  release: v$(APPVEYOR_BUILD_VERSION)-dev
  description: 'Development - v$(APPVEYOR_BUILD_VERSION)'
  prerelease: true
  draft: true
  auth_token:
    secure: riuun7iAbRmIkLsYhZqe58U99H/PnROepaggimQhrrp8p8gUOCYD2CyrjwvDzPdF
  on:
    branch: master
