name: $(Date:yy.MM)$(Rev:.r)

trigger:
- master
- dev

pr:
- master
- dev

resources:
- repo: self
  clean: false
  fetchDepth: 5

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  solution: '$(Build.Repository.LocalPath)\source\EvcProver.sln'
  project: 'source\Client.Desktop.Wpf\Client.Desktop.Wpf.csproj'
  buildPlatform: 'Any CPU'
  verbosityLevel: 'minimal'


jobs:
  - job: Windows
    steps:

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        arguments: '$(solution) -p:Version=$(Build.BuildNumber) -p:FileVersion=$(Build.BuildNumber) --configuration $(buildConfiguration) --verbosity $(verbosityLevel)'     
    
    - task: VSTest@2
      displayName: Tests
      inputs:
        testSelector: 'testAssemblies'  
        testAssemblyVer2: |
          **\*tests*.dll
          !**\*TestAdapter.dll
          !**\obj\**   
          !**\Tests.Shared.dll  
        searchFolder: '$(Build.Repository.LocalPath)\build\tests\$(buildConfiguration)'
        rerunFailedTests: True
        otherConsoleOptions: '/Framework:.NETCoreApp,Version=v3.1'   

    - task: PublishBuildArtifacts@1
      displayName: Publish Binaries Artifact
      inputs:
        PathtoPublish: '$(Build.Repository.LocalPath)\build\$(buildConfiguration)'
        ArtifactName: 'v$(Build.BuildNumber)-$(Build.SourceBranchName)'
        publishLocation: 'Container'

    - task: PublishBuildArtifacts@1
      displayName: Publish Test Artifact
      inputs:
        PathtoPublish: '$(Build.Repository.LocalPath)\build\tests\$(buildConfiguration)'
        ArtifactName: 'Tests'
        publishLocation: 'Container'
