name: $(Date:yy.MM)$(Rev:.r)

trigger:
- dev

resources:
- repo: self
  clean: false
  fetchDepth: 5

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  solution: '$(Build.Repository.LocalPath)\source\EvcProver.sln'
  project: 'source\Client.Desktop.Wpf\Client.Desktop.Wpf.csproj'
  buildPlatform: 'Any CPU'
  verbosityLevel: 'detailed'

stages:
  - stage: Building
    jobs:
    - job: build
      steps:
      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          restoreSolution: '$(Build.Repository.LocalPath)\source\Devices\Tests\**\*packages.config'
          feedsToUse: 'select'
          restoreDirectory: '$(Build.Repository.LocalPath)\packages'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '$(solution) -p:Version=$(Build.BuildNumber)--configuration $(buildConfiguration) --verbosity $(verbosityLevel)'     
          
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.Repository.LocalPath)\build\$(buildConfiguration)'
          artifact: 'Release'
          publishLocation: 'pipeline'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.Repository.LocalPath)\EvcProver.nuspec'
          artifact: 'EvcProver.nuspec'
          publishLocation: 'pipeline'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.Repository.LocalPath)\build\tests\$(buildConfiguration)'
          artifact: 'Tests)'
          publishLocation: 'pipeline' 