trigger:
- dev

resources:
- repo: self
  clean: true

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  solution: 'source\EvcProver.sln'
  project: 'source\Client.Desktop.Wpf\Client.Desktop.Wpf.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  verbosityLevel: 'minimal'

steps:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'source\Devices\Tests\**\*packages.config'
    feedsToUse: 'select'
    restoreDirectory: '..\..\..\..\packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '$(solution) --configuration $(buildConfiguration) --verbosity $(verbosityLevel)' 

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: 'Tests.**.dll'
    searchFolder: 'build\tests\$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build\$(buildConfiguration)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

