trigger:
- dev

resources:
- repo: self
  clean: true

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  solution: 'source\EvcProver.sln'
  project: 'source\Client.Desktop.Wpf\Client.Desktop.Wpf.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '-v --configuration $(buildConfiguration)' 

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--solution $(solution) --configuration $(buildConfiguration) -v' 

- task: VSTest@2
  displayName: 'Unit Tests'
  inputs:
    testAssemblyVer2: |
     **\$(buildConfiguration)\*test*.dll
     !**\obj\**
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

