trigger:
- dev

resources:
- repo: self
  clean: true

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  project: 'source\Client.Desktop.Wpf\Client.Desktop.Wpf.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(project)'