trigger:
- dev

resources:
- repo: self
  clean: true

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  solution: 'source\EvcProver.sln'
  project: 'source\Client.Desktop.Wpf\Client.Desktop.Wpf.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  verbosityLevel: 'detailed'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '$(solution) --configuration $(buildConfiguration) --verbosity $(verbosityLevel)' 

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build\$(buildConfiguration)'
    ArtifactName: 'drop'
    publishLocation: 'Container'