name: EvcProver_v$(Date:yy.MM)$(Rev:.r)_$(SourceBranchName)

trigger:
- dev

resources:
- repo: self
  clean: false
  fetchDepth: 5

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  solution: '$(Build.Repository.LocalPath)\source\EvcProver.sln'
  project: 'source\Client.Desktop.Wpf\Client.Desktop.Wpf.csproj'
  buildPlatform: 'Any CPU'
  verbosityLevel: 'minimal'

stages:
  - stage: Building
    jobs:
    - job: build
      steps:
  
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '$(solution) -p:Version=4.0.0.0 --configuration $(buildConfiguration) --verbosity $(verbosityLevel)'     
      
      - task: VSTest@2
        displayName: Tests
        inputs:
          testSelector: 'testAssemblies'  
          testAssemblyVer2: |
            **\*tests*.dll
            !**\*TestAdapter.dll
            !**\obj\**     
          searchFolder: '$(Build.Repository.LocalPath)\build\tests\$(buildConfiguration)'
          otherConsoleOptions: '/Framework:.NETCoreApp,Version=v3.1'   

      - task: PublishBuildArtifacts@1
        displayName: Publish Binaries Artifact
        inputs:
          PathtoPublish: '$(Build.Repository.LocalPath)\build\$(buildConfiguration)'
          ArtifactName: 'Binaries'
          publishLocation: 'Container'

      - task: PublishBuildArtifacts@1
        displayName: Publish Test Artifact
        inputs:
          PathtoPublish: '$(Build.Repository.LocalPath)\build\tests\$(buildConfiguration)'
          ArtifactName: 'Tests'
          publishLocation: 'Container'
       
