name: EvcProver_$(SourceBranchName)_$(Build.BuildId)

trigger:
- dev

resources:
- repo: self
  clean: false
  fetchDepth: 5

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  solution: 'source\EvcProver.sln'
  project: 'source\Client.Desktop.Wpf\Client.Desktop.Wpf.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  verbosityLevel: 'minimal'
  versionNumber: $(Date:yy.MM).$(Rev:.r)

stages:
  - stage: Build
    jobs:
    - job: A
      steps:
      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          restoreSolution: 'source\Devices\Tests\**\*packages.config'
          feedsToUse: 'select'
          restoreDirectory: '..\..\..\..\packages'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '$(solution) --configuration $(buildConfiguration) --verbosity $(verbosityLevel)' 
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'build\$(buildConfiguration)'
          ArtifactName: '$(Build.BuildNumber)'
          publishLocation: 'Container'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'build\tests\$(buildConfiguration)'
          ArtifactName: 'Tests_$(Build.BuildNumber)'
          publishLocation: 'Container'
  
  - stage: Testing
    jobs:
    - job: UnitTests
      steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'specific'
          itemPattern: 'Tests_$(Build.BuildNumber)/**'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: VSTest@2
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: 'Tests.**.dll'
          searchFolder: '$(System.ArtifactsDirectory)'
