name: $(Build.BuildId)-$(Build.SourceBranchName)

trigger: none

resources:
- repo: self
  clean: false
  fetchDepth: 5

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  solution: '$(Build.Repository.LocalPath)\source\EvcProver.sln'
  project: '$(Build.Repository.LocalPath)\source\Prover.UI.Desktop\Prover.UI.Desktop.csproj'
  buildPlatform: 'Any CPU'
  verbosityLevel: 'minimal'


jobs:
  - job: Windows
    steps:

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        arguments: '$(solution) -p:Version=1.0.$(Build.BuildId) -p:FileVersion=1.0.$(Build.BuildId) --configuration $(buildConfiguration) --verbosity $(verbosityLevel)'     
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: 'source/*.sln'

    - task: VSTest@2
      displayName: Tests
      inputs:
        testSelector: 'testAssemblies'  
        testAssemblyVer2: |
          **\*tests*.dll
          !**\*TestAdapter.dll
          !**\obj\**   
          !**\Tests.Shared.dll  
        searchFolder: '$(Build.Repository.LocalPath)\build\tests\$(buildConfiguration)'
        rerunFailedTests: True
        otherConsoleOptions: '/Framework:.NETCoreApp,Version=v3.1'   

    - task: PublishBuildArtifacts@1
      displayName: Publish Binaries Artifact
      inputs:
        PathtoPublish: '$(Build.Repository.LocalPath)\build\$(buildConfiguration)'
        ArtifactName: 'Binaries'
        publishLocation: 'Container'

    - task: PublishBuildArtifacts@1
      displayName: Publish Test Artifact
      inputs:
        PathtoPublish: '$(Build.Repository.LocalPath)\build\tests\$(buildConfiguration)'
        ArtifactName: 'Tests'
        publishLocation: 'Container'
