name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    

  
jobs:
 
  build:

    runs-on: windows-latest
    env:
      solution_path: source/Evc-Prover.sln
                  
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Current Directory
      run: ls
    - name: Install dependencies
      run: dotnet restore $solution_path
    - name: Build
      run: dotnet build --configuration Release --no-restore $solution_path
    - name: Test
      run: dotnet test --no-restore --verbosity normal $solution_path

